0.21.0+cpu

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

Invalid input. Must be one of ('y', 'yes', '1', 'n', 'no', '0', '')
Traceback (most recent call last):
  File "D:\Uncertainity Analysis-Ferhat\week5\titan.py", line 36, in <module>
    login()
    ~~~~~^^
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 31, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\_login.py", line 130, in login
    interpreter_login(new_session=new_session)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 31, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\_login.py", line 290, in interpreter_login
    _login(token=token, add_to_git_credential=add_to_git_credential)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\_login.py", line 404, in _login
    token_info = whoami(token)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\hf_api.py", line 1661, in whoami
    headers=self._build_hf_headers(token=effective_token),
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\hf_api.py", line 9102, in _build_hf_headers
    return build_hf_headers(
        token=token,
    ...<3 lines>...
        headers=self.headers,
    )
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_headers.py", line 126, in build_hf_headers
    token_to_send = get_token_to_send(token)
  File "C:\Users\aynaz\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\utils\_headers.py", line 159, in get_token_to_send
    raise LocalTokenNotFoundError(
    ...<4 lines>...
    )
huggingface_hub.errors.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
[0m
